### ISSUE TITLE
Kills GUI then stops

### ISSUE THREAD

**Issue by michaelahess** [j-c-m/ubnt-letsencrypt#16]
Installed on ER4 and upon initial script run, GUI is shut down, and the script seems to hang. Have to break out and restart GUI manually. Version 1.10.

**Comment by j-c-m** [comment]
Did you have a browser open to the GUI?

Under 1.10 it appears the GUI server will not shutdown gracefully if there is an open connection to it.

**Comment by michaelahess** [comment]
That was it, thank you this works very well!
