### ISSUE TITLE
A record needed

### ISSUE THREAD

**Issue by bwoodruff** [j-c-m/ubnt-letsencrypt#18]
THANK YOU. This worked great on my EdgeRouter.

I did run into one hiccup and that is the FQDN you use MUST be associated with an A record. It will NOT work with a CNAME record. I had a CNAME record established because my primary DNS provider doesn't support the dyndns protocol for dynamic IP updates. I had to delete that and create an A record. May be worth mentioning this in the README. 

One other suggestion is to start at the top by saying all of these commands are to be performed on the EdgeRouter. I was initially confused as to if I could / should run the Install acme.sh & scripts portion on my computer.

A question: does the hostname need to continue to resolve externally in order for this to continue to work? What happens if the A record is deleted, or replaced with a CNAME record? Or if the IP address on the A record no longer matches the IP address of the EdgeRouter?

**Comment by j-c-m** [comment]
For the automatic renewal to work the A record will need to be kept pointed to the IP of the device.  There is quite a bit of slack time (weeks) in the process so it would be possible to manually maintain the A record if that is what you had to do.

**Comment by bwoodruff** [comment]
Thanks. Looking at transitioning to Google for DNS so I can use dyndns
