### ISSUE TITLE
--force flag doesn't work

### ISSUE THREAD

**Issue by Baenwort** [j-c-m/ubnt-letsencrypt#23]
I tried to run renew.acme.sh to get a new certificate before going on vacation for an extended time. It gave me an error about it not being due (which is correct) and suggested that I use '--force' to proceed.

I am unable to get this argument to work. It doesn't work at the start or the end of the command argument list.

[Sat Sep 29 18:51:19 CDT 2018] Stopping GUI service.
[Sat Sep 29 18:51:21 CDT 2018] Starting temporary ACME challenge service.
[Sat Sep 29 18:51:24 CDT 2018] Domains not changed.
[Sat Sep 29 18:51:24 CDT 2018] Skip, Next renewal time is: Wed Oct 31 05:26:25 UTC 2018
[Sat Sep 29 18:51:24 CDT 2018] Add '--force' to force to renew.
[Sat Sep 29 18:51:24 CDT 2018] Stopping temporary ACME challenge service.

`sudo /config/scripts/renew.acme.sh -d mydomain.com -d additionaldomain.com -d additionaldomain.com -d additionaldomain.com --force -i eth0
/config/scripts/renew.acme.sh: illegal option -- -
Usage: /config/scripts/renew.acme.sh -d <mydomain.com> [-d <additionaldomain.com>]
`
I wish to do this as I haven't yet automated the updating of some of the additionaldomain.com jails and have to perform the movement manually.

**Comment by j-c-m** [comment]
The rewew.acme.sh does not accept the --force option, internally acme.sh can, and this is displayed in the log.

You can temporarily add --force to renew.acme.sh line 76 if you want to force.

**Comment by Baenwort** [comment]
Thank you for the assistance.

On Oct 1, 2018 22:48, "Jesse Miller" <notifications@github.com> wrote:

The rewew.acme.sh does not accept the --force option, internally acme.sh
can, and this is displayed in the log.

You can temporarily add --force to renew.acme.sh line 76 if you want to
force.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/j-c-m/ubnt-letsencrypt/issues/23#issuecomment-426139559>,
or mute the thread
