### ISSUE TITLE
Support for 2.x.x

### ISSUE THREAD

**Issue by charlieball** [j-c-m/ubnt-letsencrypt#26]
Can you add support for 2.x.x?

**Comment by j-c-m** [comment]
I am not testing on 2.x.x yet.  A fix for 2.x.x was added in #24 and @jmb12686  said he was on 2.0.0.

It might work?

**Comment by charlieball** [comment]
It could be that I'm missing something, but I can't get it to work.

The initial script is unable to open 443 to verify my domain.

[Sun Apr 28 11:24:17 CEST 2019] Stopping GUI service.
[Sun Apr 28 11:24:17 CEST 2019] Starting temporary ACME challenge service.
2019-04-28 11:24:17: (network.c.313) can't bind to socket: 0.0.0.0:80 Address already in use
[Sun Apr 28 11:24:19 CEST 2019] Create account key ok.
[Sun Apr 28 11:24:19 CEST 2019] Registering account
[Sun Apr 28 11:24:21 CEST 2019] Registered
[Sun Apr 28 11:24:21 CEST 2019] ACCOUNT_THUMBPRINT='redacted'
[Sun Apr 28 11:24:21 CEST 2019] Creating domain key
[Sun Apr 28 11:24:27 CEST 2019] The domain key is here: /config/.acme.sh/mydomain/mydomain.key
[Sun Apr 28 11:24:27 CEST 2019] Single domain='mydomain'
[Sun Apr 28 11:24:27 CEST 2019] Getting domain auth token for each domain
[Sun Apr 28 11:24:28 CEST 2019] Getting webroot for domain='mydomain'
[Sun Apr 28 11:24:29 CEST 2019] Verifying: mydomain
[Sun Apr 28 11:24:32 CEST 2019] Pending
[Sun Apr 28 11:24:35 CEST 2019] Pending
[Sun Apr 28 11:24:37 CEST 2019] Pending
[Sun Apr 28 11:24:40 CEST 2019] mydomain:Verify error:Fetching https://mydomain:443/.well-known/acme-challenge/redacted: Timeout during connect (likely firewall problem)
[Sun Apr 28 11:24:40 CEST 2019] Please add '--debug' or '--log' to check more details.
[Sun Apr 28 11:24:40 CEST 2019] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Sun Apr 28 11:24:41 CEST 2019] Stopping temporary ACME challenge service.
[Sun Apr 28 11:24:41 CEST 2019] Starting GUI service.
2019-04-28 11:24:41: (network.c.313) can't bind to socket: 0.0.0.0:80 Address already in use

**Comment by charlieball** [comment]
This was not a bug, it was a problem with my configuration. I wiped a settings and tried it again, now everything is working.
