### ISSUE TITLE
acme.sh no longer likes to be run with sudo

### ISSUE THREAD

**Issue by joeshaw** [j-c-m/ubnt-letsencrypt#27]
Installing newly on an Edgerouter:

```
$ sudo /config/scripts/renew.acme.sh -d router.example.org
[Fri Oct 18 22:35:09 EDT 2019] Stopping GUI service.
[Fri Oct 18 22:35:34 EDT 2019] Starting temporary ACME challenge service.
It seems that you are using sudo, please read this link first:
https://github.com/Neilpang/acme.sh/wiki/sudo
[Fri Oct 18 22:35:34 EDT 2019] Stopping temporary ACME challenge service.
[Fri Oct 18 22:35:35 EDT 2019] Starting GUI service.
```

Adding `--force` to the acme.sh invocation fixes it, but feels like a blunt hammer.

**Comment by j-c-m** [comment]
Seems like --force for now is the option, going to track upstream on this for a bit.

https://github.com/Neilpang/acme.sh/issues/2462
https://github.com/Neilpang/acme.sh/pull/2488

**Comment by joeshaw** [comment]
Bleh.  This is especially annoying because `--force` also forces renewal of the cert even if it isn't time to do so.  Hoping that PR gets merged soon.

**Comment by j-c-m** [comment]
Yep, fixed here by fooling the sudo detection in acme.sh.

f4ac0f1972ee841146cf7bb52e4ec6c059801ac8

**Comment by joeshaw** [comment]
😂 lol!  thanks for that.
