### ISSUE TITLE
Failing on verification

### ISSUE THREAD

**Issue by rpetty** [j-c-m/ubnt-letsencrypt#3]
First off, thanks for creating this.  I've been looking for a way to automate what has been a difficult task on the Edgerouter.

I believe I have followed your installation and setup instructions explicitly. 

```
root@gw1# sudo /config/scripts/renew.acme.sh -d subdomain.domain.com -i eth0
2017-04-17 02:20:23: (network.c.409) can't bind to port: XX.XX.XX.XX 80 Address already in use 
[Mon Apr 17 02:20:42 EDT 2017] Registering account
[Mon Apr 17 02:20:43 EDT 2017] Registered
[Mon Apr 17 02:20:45 EDT 2017] Update success.
[Mon Apr 17 02:20:46 EDT 2017] ACCOUNT_THUMBPRINT='XXXXXXXXXXXXXXXXXXXXXXXX'
[Mon Apr 17 02:20:46 EDT 2017] Creating domain key
[Mon Apr 17 02:20:52 EDT 2017] Single domain='subdomain.domain.com'
[Mon Apr 17 02:20:53 EDT 2017] Getting domain auth token for each domain
[Mon Apr 17 02:20:53 EDT 2017] Getting webroot for domain='subdomain.domain.com'
[Mon Apr 17 02:20:53 EDT 2017] Getting new-authz for domain='subdomain.domain.com'
[Mon Apr 17 02:20:54 EDT 2017] The new-authz request is ok.
[Mon Apr 17 02:20:55 EDT 2017] Verifying:subdomain.domain.com
[Mon Apr 17 02:20:59 EDT 2017] subdomain.domain.com:Verify error:Invalid response from http://subdomain.domain.com/.well-known/acme-challenge/xQ_TfskOZj9sizeYS7e0WbSAwwxZAh8TVk2m2tGbNWE: 
[Mon Apr 17 02:20:59 EDT 2017] Please add '--debug' or '--log' to check more details.
[Mon Apr 17 02:20:59 EDT 2017] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
```
I am replacing subdomain.domain.com with the FQDN of my router, reachable from the Internet.  I did attempt to run --debug on acme.sh.  Any thoughts on why this is failing?

**Comment by j-c-m** [comment]
Assuming XX.XX.XX.XX is your WAN IP.  This issue appears to be that the internal web gui service is still listening on your external WAN IP.  Which means the temporary service cannot listen to provide the challenge response to acme.

Verify that only your internal LAN IP is listed as a listen-address for the service.

$ configure
# show service gui

**Comment by j-c-m** [comment]
More followup, after giving it some thought, I have modified the scripts to temporarily stop the gui service during the acme challenge step (1ca5ec0).   This removes the requirement to alter an listen-address settings for the gui service.  Fetch the upgraded scripts and let me know if it works as-is.

**Comment by rpetty** [comment]
Thank you.  I will pull and test.
