### ISSUE TITLE
Not working for me. Any known issues with Dyn DNS?

### ISSUE THREAD

**Issue by VasuInukollu** [j-c-m/ubnt-letsencrypt#37]
[Thu Apr  1 10:19:40 UTC 2021] home.domain.com:Verify error:No valid IP addresses found for home.domain.com
[Thu Apr  1 10:19:40 UTC 2021] Please add '--debug' or '--log' to check more details.
[Thu Apr  1 10:19:40 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh

**Comment by dkelll** [comment]
I'm not great at cert troubleshooting so go easy please 😄 

Is your CNAME and/or A record setup properly? Has there been enough time for it to propagate?
