### ISSUE TITLE
Verify error:Invalid response from http://

### ISSUE THREAD

**Issue by TeslaOwnerTips** [j-c-m/ubnt-letsencrypt#38]
Thank you for this solution!

`[Thu Apr 22 16:01:54 EDT 2021] Verifying: x.x.com
[Thu Apr 22 16:01:58 EDT 2021] x.x.com:Verify error:Invalid response from http://x.x.com/.well-known/acme-challenge/qWnOyp_vXMXpRdTI2nv1v4NKFfXw2IL_oWjxiTD8WRo [x.x.x.x]: 
[Thu Apr 22 16:01:58 EDT 2021] Please add '--debug' or '--log' to check more details.
[Thu Apr 22 16:01:58 EDT 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Thu Apr 22 16:01:59 EDT 2021] Stopping temporary ACME challenge service.`

**Comment by j-c-m** [comment]
The script temporarily disables the EdgeOS GUI service already.

https://github.com/j-c-m/ubnt-letsencrypt/blob/master/renew.acme.sh#L63-L66

Something else is probably the issue here, anything in /config/.acme.sh/lighttpd.log ?

**Comment by TeslaOwnerTips** [comment]
admin@ubnt:/config/scripts$ cat /config/.acme.sh/lighttpd.log 
192.168.1.13 192.168.1.1 - [22/Apr/2021:16:01:54 -0400] "GET /auth/discovery HTTP/1.1" 404 345 "-" "-"
192.168.1.13 192.168.1.1 - [22/Apr/2021:16:31:54 -0400] "GET /auth/discovery HTTP/1.1" 404 345 "-" "-"

**Comment by TeslaOwnerTips** [comment]
Let me get back to you. I want to do a reboot and start fresh.
I have to wait till after 5pm DST

**Comment by TeslaOwnerTips** [comment]
May I PM you so I can show you my IPs etc?

**Comment by j-c-m** [comment]
Sure e-mail is fine.

**Comment by TeslaOwnerTips** [comment]
I had used a subdomain redirect.
Changed to an A Record. Works:)
Thank you for this.
If my ip changes I guess I'll have to do the process again.
