### ISSUE TITLE
set system static-host-mapping not needed?

### ISSUE THREAD

**Issue by rogerthn2019** [j-c-m/ubnt-letsencrypt#43]
Running EdgeRouter Lite v1.10.11 and with LAN IP of Router and FQDN in the hosts file on my browsing computer `set system static-host-mapping` seems to be redundant.
Might help someone.

**Comment by j-c-m** [comment]
With an alternative resolution, such as the hosts file on all local machines, one side would be redundant. Generally I think people rely on it rather than managing the hosts files on the local machines.
