### ISSUE TITLE
Could not connect to

### ISSUE THREAD

**Issue by tylercal** [j-c-m/ubnt-letsencrypt#7]
I've verified that I've set my DNS to my WAN IP, but am now getting caught up on I assume a firewall:

```
[Fri May  5 21:49:19 PDT 2017] The new-authz request is ok.
[Fri May  5 21:49:20 PDT 2017] Verifying:router.roomj.com
[Fri May  5 21:49:24 PDT 2017] Pending
[Fri May  5 21:49:26 PDT 2017] Pending
[Fri May  5 21:49:29 PDT 2017] router.roomj.com:Verify error:Could not connect to router.roomj.com
[Fri May  5 21:49:29 PDT 2017] Please add '--debug' or '--log' to check more details.
[Fri May  5 21:49:29 PDT 2017] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
```

**Comment by j-c-m** [comment]
It has to connect to port 80 on your router, it does its best to temporarily open port 80, but if you have some other rules around port 80 (maybe a port forward?) that may interfere.

**Comment by tylercal** [comment]
Yeah, everything looks like port 80 should be open but something is stopping or stealing the traffic. It seems that I can't get the router to listen on any port for traffic from the wan (port forwarding to LAN devices on other ports work though). 

I'll have to debug this separately, thanks for the pointer.

**Comment by tylercal** [comment]
I'm not exactly sure what the problem with my configuration was. My best guess is that I had a LAN bridge to eth1.

I reset the configuration on the router and everything seems to be working now. So nice to have the security warning gone.
