### ISSUE TITLE
Script failing on new setup

### ISSUE THREAD

**Issue by hulu1522** [j-c-m/ubnt-letsencrypt#8]
I keep getting these errors when trying to run `renew.acme.sh` for the first time.  I have done with your instructions say and also the closed issue about using this for WAN IP.  Is there certain ports that need to be exposed?

```
[Tue May 30 17:50:43 MDT 2017] Stopping gui service.
[Tue May 30 17:50:43 MDT 2017] Starting temporary acme challenge service.
[Tue May 30 17:50:43 MDT 2017] Unknown parameter : /tmp/server.key
[Tue May 30 17:50:43 MDT 2017] Stopping temporary acme challenge service.
[Tue May 30 17:50:44 MDT 2017] Starting gui service.
2017-05-30 17:50:44: (network.c.537) SSL: BIO_read_filename('/config/ssl/server.pem') failed
```

Thanks for your help on this issue.

**Comment by j-c-m** [comment]
What is the full command you ran for the initial renew.acme.sh.

**Comment by hulu1522** [comment]
`sudo /config/scripts/renew.acme.sh -d my.domain.com -i eth1`

I have `eth1` as my main WAN.

**Comment by hulu1522** [comment]
So I got it working... I'm sorry for the issue.  My ISP is connected to `eth1` but it is a PPPoE connection.  After changing the command to use `pppoe0` it worked just fine.  Thanks again for this awesome integration for the EdgeRouter.

**Comment by j-c-m** [comment]
Good to hear, the script should probably error when it can't determine the WANIP.  What does this display when executed on your configuration?

```
ip addr show eth1 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1
```

**Comment by j-c-m** [comment]
Added check 4c1f78ff82187fa24583b696b8d1de4313219f10

**Comment by hulu1522** [comment]
@j-c-m 

Here is the output of the command.  I split it into each element to see where the output came from.  My ISP is DSL with PPPoE.

```
eve@ER-Main:~$ ip addr show eth1 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1
eve@ER-Main:~$ ip addr show eth1 | grep "inet\b" | awk '{print $2}'
eve@ER-Main:~$ ip addr show eth1 | grep "inet\b"
eve@ER-Main:~$ ip addr show eth1
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default
    link/ether 24:a4:3c:05:b6:d6 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::26a4:3cff:fe05:b6d6/64 scope link
       valid_lft forever preferred_lft forever
```
